import { Signer, utils } from 'ethers';
import { ACTPMessage, DeliveryProof } from '../types';
import { SignatureVerificationError } from '../errors';
import {
  EIP712Domain,
  getMessageTypes,
  QuoteRequestData,
  QuoteResponseData,
  DeliveryProofData,
  deliveryProofDataFromProof
} from '../types/eip712';
import { IReceivedNonceTracker } from '../utils/ReceivedNonceTracker';

// Legacy generic ACTP message types moved to types/eip712.ts

/**
 * TypeScript interface for ethers v5 Signer with _signTypedData method
 *
 * Note: _signTypedData exists in ethers v5 runtime but is not in official type definitions.
 * This interface properly types the method to avoid @ts-ignore comments.
 */
interface SignerWithTypedData extends Signer {
  _signTypedData(
    domain: EIP712Domain,
    types: Record<string, any>,
    value: Record<string, any>
  ): Promise<string>;
}

/**
 * MessageSigner - Cryptographic signing for ACTP messages with EIP-712
 * Reference: Yellow Paper §11.4.2
 *
 * V4 Security Enhancement: Optional nonce replay protection via ReceivedNonceTracker
 */
export class MessageSigner {
  private domain: EIP712Domain | null = null;

  constructor(
    private readonly signer: Signer,
    private readonly nonceTracker?: IReceivedNonceTracker
  ) {}

  /**
   * Initialize EIP-712 domain (must be called before signing)
   * @param kernelAddress - Address of ACTP Kernel contract
   * @param chainId - Optional chainId (defaults to signer's chainId or 84532 for Base Sepolia)
   */
  async initDomain(kernelAddress: string, chainId?: number): Promise<void> {
    let resolvedChainId: number;

    if (chainId !== undefined) {
      resolvedChainId = chainId;
    } else {
      try {
        resolvedChainId = await this.signer.getChainId();
      } catch (error) {
        // Fallback to Base Sepolia for testing without provider
        resolvedChainId = 84532;
      }
    }

    this.domain = {
      name: 'ACTP',
      version: '1.0',
      chainId: resolvedChainId,
      verifyingContract: kernelAddress
    };
  }

  /**
   * Sign ACTP message using EIP-712 typed data
   * Uses ECDSA (secp256k1) with domain separation per Yellow Paper §11.4.2
   * 
   * Generic ACTPMessage format (backward compatible).
   * For strict typed AIP messages, use signQuoteRequest/signQuoteResponse/signDeliveryProof
   */
  async signMessage(message: ACTPMessage): Promise<string> {
    if (!this.domain) {
      throw new Error('Domain not initialized. Call initDomain() first.');
    }

    const { type, version, from, to, timestamp, nonce, signature, ...payload } = message;

    // Generic ACTPMessage with payload encoding (backward compatible)
    const payloadBytes = utils.defaultAbiCoder.encode(
      ['string'],
      [this.canonicalizePayload(payload)]
    );

    const typedMessage = {
      type,
      version,
      from,
      to,
      timestamp,
      nonce,
      payload: payloadBytes
    };

    // Use generic ACTPMessage types
    const messageTypes = getMessageTypes('default');

    // Sign using EIP-712
    const signer = this.signer as SignerWithTypedData;
    const sig = await signer._signTypedData(this.domain, messageTypes, typedMessage);

    return sig;
  }

  /**
   * Sign typed QuoteRequest message
   */
  async signQuoteRequest(data: QuoteRequestData): Promise<string> {
    if (!this.domain) {
      throw new Error('Domain not initialized. Call initDomain() first.');
    }

    const messageTypes = getMessageTypes('quote.request');
    const signer = this.signer as SignerWithTypedData;
    return await signer._signTypedData(this.domain, messageTypes, data);
  }

  /**
   * Sign typed QuoteResponse message
   */
  async signQuoteResponse(data: QuoteResponseData): Promise<string> {
    if (!this.domain) {
      throw new Error('Domain not initialized. Call initDomain() first.');
    }

    const messageTypes = getMessageTypes('quote.response');
    const signer = this.signer as SignerWithTypedData;
    return await signer._signTypedData(this.domain, messageTypes, data);
  }

  /**
   * Sign typed DeliveryProof message
   */
  async signDeliveryProof(data: DeliveryProofData): Promise<string> {
    if (!this.domain) {
      throw new Error('Domain not initialized. Call initDomain() first.');
    }

    const messageTypes = getMessageTypes('delivery.proof');
    const signer = this.signer as SignerWithTypedData;
    return await signer._signTypedData(this.domain, messageTypes, data);
  }

  /**
   * Convenience helper to sign a DeliveryProof generated by ProofGenerator
   */
  async signGeneratedDeliveryProof(proof: DeliveryProof): Promise<string> {
    const typedData = deliveryProofDataFromProof(proof);
    return await this.signDeliveryProof(typedData);
  }

  /**
   * Verify message signature using EIP-712
   * Uses generic ACTPMessage types (backward compatible)
   *
   * V4 Security: If nonceTracker is configured, validates nonce for replay protection
   */
  async verifySignature(message: ACTPMessage, signature: string): Promise<boolean> {
    if (!this.domain) {
      throw new Error('Domain not initialized. Call initDomain() first.');
    }

    const { type, version, from, to, timestamp, nonce, signature: _, ...payload } = message;

    const payloadBytes = utils.defaultAbiCoder.encode(
      ['string'],
      [this.canonicalizePayload(payload)]
    );

    const typedMessage = {
      type,
      version,
      from,
      to,
      timestamp,
      nonce,
      payload: payloadBytes
    };

    // Use generic ACTPMessage types (backward compatible)
    const messageTypes = getMessageTypes('default');
    const recoveredAddress = utils.verifyTypedData(
      this.domain,
      messageTypes,
      typedMessage,
      signature
    );

    const expectedAddress = this.didToAddress(from);

    // Verify signature matches sender
    if (recoveredAddress.toLowerCase() !== expectedAddress.toLowerCase()) {
      return false;
    }

    // V4 Security: Validate nonce for replay protection (if tracker configured)
    if (this.nonceTracker) {
      const nonceValidation = this.nonceTracker.validateAndRecord(from, type, nonce);
      if (!nonceValidation.valid) {
        // Nonce replay detected - return false
        return false;
      }
    }

    return true;
  }

  /**
   * Verify signature and throw if invalid
   * V4 Security: Throws specific error for nonce replay detection
   */
  async verifySignatureOrThrow(message: ACTPMessage, signature: string): Promise<void> {
    if (!this.domain) {
      throw new Error('Domain not initialized');
    }

    const { type, version, from, to, timestamp, nonce, signature: _, ...payload } = message;

    const payloadBytes = utils.defaultAbiCoder.encode(
      ['string'],
      [this.canonicalizePayload(payload)]
    );

    const typedMessage = { type, version, from, to, timestamp, nonce, payload: payloadBytes };

    const messageTypes = getMessageTypes('default');
    const recoveredAddress = utils.verifyTypedData(
      this.domain,
      messageTypes,
      typedMessage,
      signature
    );

    const expectedAddress = this.didToAddress(from);

    // Check signature validity first
    if (recoveredAddress.toLowerCase() !== expectedAddress.toLowerCase()) {
      throw new SignatureVerificationError(expectedAddress, recoveredAddress);
    }

    // V4 Security: Validate nonce for replay protection (if tracker configured)
    if (this.nonceTracker) {
      const nonceValidation = this.nonceTracker.validateAndRecord(from, type, nonce);
      if (!nonceValidation.valid) {
        // Throw specific error for nonce replay
        throw new Error(
          `Nonce replay attack detected: ${nonceValidation.reason}. ` +
          `Received nonce: ${nonceValidation.receivedNonce}. ` +
          (nonceValidation.expectedMinimum ? `Expected minimum: ${nonceValidation.expectedMinimum}` : '')
        );
      }
    }
  }

  /**
   * Canonicalize payload to deterministic string (recursively sorted keys)
   * Prevents JSON serialization ambiguity across different JS runtimes
   * Recursively handles nested objects and arrays
   */
  private canonicalizePayload(payload: Record<string, any>): string {
    return JSON.stringify(this.recursiveSort(payload));
  }

  /**
   * Recursively sort object keys for deterministic JSON encoding
   */
  private recursiveSort(obj: any): any {
    if (obj === null || obj === undefined) {
      return obj;
    }

    // Handle arrays: recursively sort each element
    if (Array.isArray(obj)) {
      return obj.map((item) => this.recursiveSort(item));
    }

    // Handle objects: sort keys and recursively sort values
    if (typeof obj === 'object' && obj.constructor === Object) {
      const sortedKeys = Object.keys(obj).sort();
      const canonical: Record<string, any> = {};

      for (const key of sortedKeys) {
        canonical[key] = this.recursiveSort(obj[key]);
      }

      return canonical;
    }

    // Primitives (string, number, boolean)
    return obj;
  }

  /**
   * Convert DID to Ethereum address
   * MVP: Simple did:ethr → address conversion
   */
  private didToAddress(did: string): string {
    if (did.startsWith('did:ethr:')) {
      return did.replace('did:ethr:', '');
    }

    // If already an address, return as-is
    if (utils.isAddress(did)) {
      return did;
    }

    throw new Error(`Invalid DID format: ${did}`);
  }

  /**
   * Convert Ethereum address to DID
   */
  addressToDID(address: string): string {
    if (!utils.isAddress(address)) {
      throw new Error(`Invalid Ethereum address: ${address}`);
    }

    return `did:ethr:${address}`;
  }
}
